config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path_names: { sign_up: 'register_not_allowed' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  authenticate :user do 
    resources :patients
    resources :doctors
    resources :users
    get "/dashboard", :to => "dashboards#index"
    post "/dashboard", :to => "dashboards#index"
    root to: "patients#index"
  end
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/views/layouts/_header.html.erb
<nav class="bg-white dark:bg-gray-900 border-gray-200 dark:border-gray-600 w-[100%]">
	<div class="max-w-screen-xl flex flex-wrap items-center justify-end mx-auto p-4">
		<div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
			<button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
				<span class="sr-only">Open user menu</span>
				<div class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
					<svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
				</div>
			</button>
			<!-- Dropdown menu -->
			<div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
				<div class="px-4 py-3">
					<span class="block text-sm text-gray-900 dark:text-white"><%= current_user.name %></span>
					<span class="block text-sm  text-gray-500 truncate dark:text-gray-400"><%= current_user.email %></span>
				</div>
				<div class="px-4 py-1">
					<span class="block text-sm  text-gray-500 truncate dark:text-gray-400"><%= current_user.role %></span>
				</div>
				<ul class="py-2" aria-labelledby="user-menu-button">
					<li>
						<%= button_to "Sign out", destroy_user_session_path(user_session), method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
					</li>
				</ul>
			</div>
			<button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
				<span class="sr-only">Open main menu</span>
				<svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
					<path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
				</svg>
			</button>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
	<span class="sr-only">Open sidebar</span>
	<svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
		<path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
	</svg>
</button>
<aside id="default-sidebar" class="fixed w-[20%] top-0 left-0 z-40 h-screen transition-transform -translate-x-full sm:translate-x-0 border-solid border-r-[1px] border-slate-200 " aria-label="Sidebar">
	<div class="h-full px-3 py-4 overflow-y-auto bg-white dark:bg-gray-800">
		<a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse text-gray-900 mb-5">
			<img src="https://play-lh.googleusercontent.com/gA1ndg-MAug5fuO_x4DNmOzB-K1yGJRBn6PAnv7w0DMlX5uHpS0sFfGiT-RWPpsq3oM" class="h-8" alt="Flowbite Logo">
			<span class="self-center text-2xl font-semibold whitespace-nowrap dark">Hospital</span>
		</a>
		<ul class="space-y-2 font-medium">
			<li>
				<% if can? :read, Dashboard %>
					<a href="<%= dashboard_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
						<svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
							<path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
							<path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
						</svg>
						<span class="ms-3">Dashboard</span>
					</a>
				<% end %>
			</li>
			<li>
				<% if can? :read, Patient %>
					<a href="<%= patients_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
						<svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
							<path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
						</svg>
						<span class="flex-1 ms-3 whitespace-nowrap">Patients</span>
						<span class="inline-flex items-center justify-center h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300"><%= @total_patients %></span>
					</a>
				<% end %>
			</li>
			<li>
				<% if can? :read, Receptionist %>
					<a href="<%= users_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
						<svg class="w-6 h-6 text-gray-500 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
							<path fill-rule="evenodd" d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z" clip-rule="evenodd"/>
						</svg>
						<span class="flex-1 ms-3 whitespace-nowrap">Users</span>
						<span class="inline-flex items-center justify-center h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300"><%= @total_users %></span>
					</a>
				<% end %>
			</li>
		</ul>
	</div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>WorkableApp</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
	</head>
	<body class="bg-gray-100">
		<main class="">
			<% if flash[:notice] %>
				<div class="fixed flex justify-around  w-full top-0  p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
					<%= notice %>
				</div>
			<% end %>
			<% if flash[:alert] %>
				<div class="fixed flex justify-around  w-full top-0  p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
					<%= alert %>
				</div>
			<% end %>
			<%= yield %>
		</main>
	</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>WorkableApp</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="csrf-token" content="<%= form_authenticity_token %>">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
		<%= javascript_include_tag 'turbo' %>
		<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
	</head>
	<body class="bg-gray-100">
		<main class="">
			<div class="grid grid-cols-5 gap-0">
				<div class="sidebar col-span-1  text-white h-screen ">
					<%= render 'layouts/sidebar' %>
				</div>
				<div class="col-span-4">
					<div class="flex header bg-slate-400 h-12 items-center w-[100%] z-20 top-0 start-0 border-b">
						<%= render 'layouts/header' %>
					</div>
					<div class="content p-4">
						<%= yield %>
					</div>
				</div>
			</div>
		</main>
	</body>
</html>